export const productColumns = [
  {
    key: "name",
    title: "Producto",
    width: "w-[11%] min-[1440px]:min-w-0",
    field: "name",
    className: "text-sm font-medium text-gray-900",
  },
  {
    key: "code",
    title: "Código",
    width: "w-[8%] min-[1440px]:min-w-0",
    field: "code",
    className: "text-xs font-mono text-gray-500",
  },
  {
    key: "category",
    title: "Categoría",
    width: "w-[12%] min-[1440px]:min-w-0",
    field: "category_product.name",
    className: "text-sm text-gray-600",
  },
  {
    key: "unit",
    title: "Unidad",
    width: "w-[5%] min-[1440px]:min-w-0",
    field: "unit.code",
    className: "text-sm text-gray-600 uppercase",
  },
  {
    key: "content",
    title: "Cont.",
    width: "w-[6%] min-[1440px]:min-w-0",
    field: "content_quantity",
    className: "text-sm text-gray-600",
  },
  {
    key: "minStock",
    title: "Min Stk",
    width: "w-[6%] min-[1440px]:min-w-0",
    field: "min_stock",
    className: "text-sm font-medium text-gray-700",
  },
  {
    key: "maxStock",
    title: "Max Stk",
    width: "w-[6%] min-[1440px]:min-w-0",
    field: "max_stock",
    className: "text-sm font-medium text-gray-700",
  },
  {
    key: "is_active",
    title: "Estado",
    width: "w-[8%] min-[1440px]:min-w-0",
    field: "is_active",
    className: "text-sm font-medium text-gray-700",
    render: (product) => (product.is_active ? "Activo" : "Eliminado"),
  },
];