export const productColumns = [
  {
    key: "name",
    title: "Producto",
    width: "w-[26%] min-w-[260px]",
    field: "name",
    className: "text-sm font-medium text-gray-900",
  },
  {
    key: "code",
    title: "Código",
    width: "w-[14%] min-w-[140px]",
    field: "code",
    className: "text-xs font-mono text-gray-500",
  },
  {
    key: "category",
    title: "Categoría",
    width: "w-[18%] min-w-[180px]",
    field: "category_product.name",
    className: "text-sm text-gray-600",
  },
  {
    key: "unit",
    title: "Unidad",
    width: "w-[8%] min-w-[120px]",
    field: "unit.code",
    className: "text-sm text-gray-600 uppercase",
  },
  {
    key: "content",
    title: "Cont.",
    width: "w-[8%] min-w-[140px]",
    field: "content_quantity",
    className: "text-sm text-gray-600",
  },
  {
    key: "minStock",
    title: "Min Stk",
    width: "w-[10%] min-w-[110px]",
    field: "min_stock",
    className: "text-sm font-medium text-gray-700",
  },
  {
    key: "maxStock",
    title: "Max Stk",
    width: "w-[10%] min-w-[110px]",
    field: "max_stock",
    className: "text-sm font-medium text-gray-700",
  },
];